apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "hello-app.name" . }}
spec:
  selector:
    app: {{ include "hello-app.name" . }}
  ports:
  - name: http   # 🔥 REQUIRED
    port: 80
    targetPort: 8080
